### ISSUE TITLE
Discrepancy in javascript_pack_tag between original and downstream forks of this repo

### ISSUE THREAD

**Issue by kylemichaelreaves** [kylemichaelreaves/rails-pg-app#67]
On my work laptop, the `javascript_pack_tag` in the `application.html.erb` refers to `index`…on my personal computer it's `Index`…

**Comment by KyleReaves** [comment]
This issue had something to do with the [Asset pipeline](https://guides.rubyonrails.org/asset_pipeline.html).
We were getting an error because `Index.js` in `app/assets/builds` was capitalized instead of being lowercase. This seemed to have resolved the issue, since I've pulled from upstream and started up development instances locally since, without incurring that particular error.
